name: serv00 login

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"  # 每周一6点运行一次，可以根据需求调整时间
  # push:
  #   branches:
  #     - main
jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # 设置 Python 版本，建议使用稳定版本

      - name: 随机睡眠
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-100 -n 1)

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip
          pip install playwright  # 安装playwright
          playwright install chromium  # 安装驱动

      - name: 设置变量 运行脚本
        env:
          # 需要添加Action Secrets
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }} # telgram推送，选填
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }} # telgram推送，选填
          SCKEY: ${{ secrets.SCKEY }} # serv酱推送，选填
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }} # pushplus推送，选填
          SERV_LIST: ${{ secrets.SERV_LIST }} # 必填
        run: |
          python login_script.py
